package me.bechberger.meta;

import me.bechberger.meta.runtime.InstrumentationHandler;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.*;
import java.util.Comparator;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.stream.Stream;

/**
 * Reads the files generated by the native wrapper agent in the /tmp/njvm<pid>/
 * and regularly adds their content via {@link InstrumentationHandler#addDiff(String, String, byte[], byte[])}.
 * <p>
 * This implementation doesn't use a file watcher, because the API can't deal with so
 * many files generated in fast succession.
 */
public class NativeWrapperLoop implements Runnable {

    private final AtomicBoolean stop;

    public NativeWrapperLoop(AtomicBoolean stop) {
        this.stop = stop;
    }

    public static void startThread() {
        AtomicBoolean stop = new AtomicBoolean(false);
        Thread t = new Thread(new NativeWrapperLoop(stop));
        t.setName("NativeWrapperLoop");
        t.start();
        Runtime.getRuntime().addShutdownHook(new Thread(() -> stop.set(false)));
    }

    @Override
    public void run() {
        long pid = ProcessHandle.current().pid();
        Path directory = Paths.get("/tmp/njvm" + pid);
        while (!stop.get()) {
            AtomicBoolean hasFiles = new AtomicBoolean(false);
            try (Stream<Path> stream = Files.list(directory)) {
                stream.sorted(Comparator.comparing(p -> Integer.parseInt(p.getFileName().toString()))).forEach(entry -> {
                    try {
                        processFile(directory.resolve(entry.getFileName()));
                        Files.deleteIfExists(entry);
                    } catch (Exception e) {
                    }
                    hasFiles.set(true);
                });
                if (!hasFiles.get()) {
                    Thread.sleep(10);
                }
            } catch (NoSuchFileException e) {
                // Directory does not exist yet, wait and try again
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * File format:
     * - Line 1: agent_name (e.g., "agent_minimal_cfh")
     * - Line 2: class_name (e.g., "java/lang/String" or "unknown")
     * - Line 3: old_len (decimal number, e.g., "1234")
     * - Line 4: new_len (decimal number, e.g., "1456")
     * - Binary data: old_len bytes of original class data
     * - Binary data: new_len bytes of transformed class data
     */
    private void processFile(Path filePath) {
        try (var in = Files.newInputStream(filePath)) {
            String agentName = readLine(in);
            String className = readLine(in);
            int oldLen = Integer.parseInt(readLine(in));
            int newLen = Integer.parseInt(readLine(in));
            byte[] oldBytes = in.readNBytes(oldLen);
            byte[] newBytes = in.readNBytes(newLen);
            InstrumentationHandler.addDiff(agentName, className, oldBytes, newBytes);
        } catch (NoSuchFileException e) {
            // just ignore if file is not found, this can only occur during shutdown
        } catch (IOException e) {
            // this is not expected, print stack trace
            e.printStackTrace();
        }
    }

    private String readLine(InputStream in) throws IOException {
        StringBuilder sb = new StringBuilder();
        int b;
        while ((b = in.read()) != -1) {
            if (b == '\n') {
                break;
            }
            sb.append((char) b);
        }
        return sb.toString();
    }
}